version: '3.8'
services:
    postgres:
        container_name: pg_container
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        ports:
          - "5432:5432"
      
    ms-customer-order-svc:
        ports:
            - '8080:8080'
        #environment:
            #POSTGRES_URL: postgresql://postgres:5432/postgres
        image: ms-customer-order-svc
        depends_on:
            - postgres